default:
  adapter: postgresql
  database: opres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: opres_test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: opres_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: opres_production
  pool: 5
  timeout: 5000

