default:
  adapter: postgresql
  database: opres
  pool: 5
  timeout: 5000
  username: tsc
  password: tsc_123

test:
  adapter: postgresql
  database: opres_test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: opres_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: opres_production
  pool: 5
  timeout: 5000

